name: Update EditorConfig
on:
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set Branch Name
      id: set-branch
      run: |
        echo "branch=update/upstream-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    - name: Update Stream
      run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git remote add upstream/cs-editorconfig https://github.com/AndanteTribe/cs-editorconfig.git
          git fetch upstream/cs-editorconfig

          git fetch origin
          git checkout -b "${{ steps.set-branch.outputs.branch }}" origin/main
          git merge upstream/cs-editorconfig/main --allow-unrelated-histories || true
          git push origin "${{ steps.set-branch.outputs.branch }}"
    - name: create pull request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create \
          --base main \
          --head "${{ steps.set-branch.outputs.branch }}" \
          --title "chore: update cs-editorconfig" \
          --fill \
          --assignee "${{ github.actor }}"
